spring:
    devtools:
        restart:
            enabled: false

liquibase:
    contexts: prod

server:
    port: 8080
    compression:
        enabled: true
        mime-types: text/html, text/xml, text/plain, text/css, application/javascript, application/json

debug: false

